project_id = "fyihypkigbcmsxyvseca"

[functions.stripe-create-checkout]
verify_jwt = true

[functions.stripe-customer-portal]
verify_jwt = true

[functions.stripe-check-subscription]
verify_jwt = true